### ISSUE TITLE
How this gem works?

### ISSUE THREAD

**Issue by nicodmf** [capistrano/copy-files#1]
I install the lib in Gemfile :  

``` ruby
gem 'capistrano-copy-files'
```

I added in Capfile : 

``` ruby
require 'capistrano-copy-files'
```

I added in deploy.rb

``` ruby
set :copy_files, ["vendor"]
```

But copy seems inactive.

What i should make?

My goal is to copy composer vendor directory beetween two deployments.

**Comment by martinandert** [comment]
@nicodmf The `copy_files` task expects a `app` role to be present. Did you define that role?

**Comment by nicodmf** [comment]
@martinandert thanks, at the creation issue moment i just copied the recipe and used it, and this worked. I will follow your advice for futures uses.

**Comment by alister** [comment]
I had some problems myself with this, but the following does appear to work.

Gemfile:

```
  # add
  gem 'capistrano-copy-files'
```

Capfile:

```
# add
require 'capistrano/copy_files'
```

deploy.rb:

```
# add the following to the file somewhere
set :copy_files, ["vendor"]

# ensure the 'copy_files' runs at the right time
before "composer:run",      "deploy:copy_files"
```

With this in place (on a DigitalOcean SSD drive), a copy takes ~6 secs + composer install ~15 secs, down from a fresh 'composer install' of ~1m,12s. This is with an unchanged composer.lock file.

**Comment by nicodmf** [comment]
good news :)
